Added kevq.uk
jackmcdade/weird-wide-webring pull request #29
Opened 2020-08-16 10:40 UTC by kevquirk

Added my site as I think I may just be weird enough to be included. Your call though. :smiley:

2020-08-21 07:12 UTC, kevquirk commented
Haven't heard back on this, so have removed the links from my footer. I assume that means you think my blog isn't appropriate for inclusion. That's totally cool. If you change your mind, I'll re-add them. :-)

All the best.

2021-06-30 15:59 UTC, jackmcdade commented on sites.js
>      }
Needs a comma after the brace. `},`

2021-06-30 15:59 UTC, jackmcdade requested changes
Needs a comma after that brace. Otherwise, cool site!

2021-07-01 10:50 UTC, kevquirk commented
Will re-submit.

2021-07-01 10:50 UTC, closed without merging